### 1. Create Numpy Arrays: total 50 points

In [1]:
import numpy as np

1). Convert a Python list x=[[1,2,3],[4,5,6]] into a Numpy array.

In [2]:
x=np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

Use one line to create a 3x2 2D array with shape of (3,2), filled with 1-6. 

In [3]:
q2 = np.arange(1,7).reshape(3,2)
q2

array([[1, 2],
       [3, 4],
       [5, 6]])

3). Use one line to create an array of 2, 4, 6, 8, ..., 98, 100; and find the mean value. 

In [4]:
q3 = np.arange(2,101).mean()
q3

51.0

4). Create an 3x3x3 array filled with arbitrary float numbers; and find the minimum and maximum values. 

In [5]:
q4 = np.random.rand(3, 3, 3)
print(q4)
minq4 = q4.min()
print("Minimum value is: ")
print(minq4)
maxq4 = q4.max()
print("Maximum value is: ")
print(maxq4)

[[[0.80194609 0.84442174 0.60458262]
  [0.70488754 0.84790967 0.359724  ]
  [0.32410548 0.43987175 0.85772322]]

 [[0.48663    0.93702691 0.40908856]
  [0.81606305 0.54390856 0.75652079]
  [0.70679984 0.81215034 0.73383134]]

 [[0.76728733 0.84989972 0.36068875]
  [0.15387992 0.6287457  0.40344215]
  [0.46383066 0.37320246 0.74865531]]]
Minimum value is: 
0.15387991932067868
Maximum value is: 
0.9370269126892685


5). Create a 3x4 2D array filled with values from 10 to 21 (included).

In [6]:
q5 = np.arange(10,22).reshape(3,4)
q5

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

6). Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers.

In [7]:
q6 = np.arange(5, 35, 3) #5+10*3 = 35
q6

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

7). Create a shape (10,10) array with arbitrary values; and find the memory size of this array.  

In [8]:
rng = np.random.default_rng(seed=21)
q7 = rng.integers(10, size=(10, 10))
print(q7)
sizeq7 = q7.nbytes
print("Memory size is: "+str(sizeq7))

[[3 7 3 6 4 7 3 0 2 6]
 [6 9 2 4 9 1 7 9 9 6]
 [8 1 7 6 5 9 8 2 9 8]
 [3 6 7 2 2 1 4 9 3 3]
 [9 4 0 6 7 4 9 0 8 2]
 [7 4 6 7 8 6 6 4 0 1]
 [1 7 1 1 2 7 3 4 6 5]
 [4 3 9 2 7 1 4 6 2 2]
 [1 0 2 1 6 9 0 7 4 5]
 [9 4 1 8 8 2 5 6 1 0]]
Memory size is: 800


8). Create a 1-d array of size 10 with arbitrary values but the fifth value should be 5. 

In [9]:
rng = np.random.default_rng(seed=21)
q8 = rng.integers(10, size=10)
print("Original array: "+str(q8))

q8[4] = 5
print("Array with 5th value as 5: ")
print(q8)

Original array: [3 7 3 6 4 7 3 0 2 6]
Array with 5th value as 5: 
[3 7 3 6 5 7 3 0 2 6]


9). Create an array with values ranging from 10 to 49 (included); and reverse it then (first element becomes last). 

In [10]:
q9 = np.arange(10,50)
print("Original array: ")
print(q9)

reverseq9 = q9[::-1]
print("New array: ")
print(reverseq9)

Original array: 
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
New array: 
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


10). Create an array of shape (3, 2) with random values from a uniform distribution over [0, 1) and confirm you can get the same value when you run it next time.

In [11]:
import numpy as np

np.random.seed(21)
q10 = np.random.rand(3, 2)
print("Original Array:")
print(q10)

print("New Array:")
print(q10)

Original Array:
[[0.04872488 0.28910966]
 [0.72096635 0.02161625]
 [0.20592277 0.05077326]]
New Array:
[[0.04872488 0.28910966]
 [0.72096635 0.02161625]
 [0.20592277 0.05077326]]


11). Create a 5x5 matrix with row values ranging from 0 to 4:

[[0. 1. 2. 3. 4.]

 [0. 1. 2. 3. 4.]

 [0. 1. 2. 3. 4.]

 [0. 1. 2. 3. 4.]

 [0. 1. 2. 3. 4.]]

In [12]:
import numpy as np
q11 = np.zeros((5,5))
print(q11)
a = np.arange(5)
print(a)
M = q11+a
print(M)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0 1 2 3 4]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


12). Add a border (filled with 0's) around an existing array:

[[1. 1. 1. 1. 1.]

 [1. 1. 1. 1. 1.]

 [1. 1. 1. 1. 1.]

 [1. 1. 1. 1. 1.]

 [1. 1. 1. 1. 1.]]

In [13]:
import numpy as np
q12 = np.ones((5,5))
print("Existing array: ")
print(q12)
q12 = np.pad(q12, 1, 'constant', constant_values=0)
print("New array: ")
print(q12)

Existing array: 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
New array: 
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


13). Create a 5x5 2-d array with values 1,2,3,4,5 on the diagonal (3 points)

[1 0 0 0 0]

 [0 2 0 0 0]

 [0 0 3 0 0]

 [0 0 0 4 0]

 [0 0 0 0 5]]
Then, make 1,2,3,4 move below the diagonal: (3 points)

[[0 0 0 0 0]

 [1 0 0 0 0]

 [0 2 0 0 0]

 [0 0 3 0 0]

 [0 0 0 4 0]]


In [14]:
q13 = np.zeros((5,5), dtype = int)
for i in range(5):
    q13[i,i] = i+1
print("5x5 2D array is :")
print(q13)

for i in range(4):
    q13[i+1,i] = i+1
    q13[i,i] = 0
    q13[i+1,i+1] = 0
print("New array is :")
print(q13)

5x5 2D array is :
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
New array is :
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


14). Create a 10x10 2-d array with 1 (2 point) on the border and 0 inside (4 points).

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [15]:
q14 = np.zeros((10,10))
q14[0,] = 1
q14[-1,] = 1
q14[:,0] = 1
q14[:,-1] = 1
q14

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

15). Extract the integer part of a random array of positive numbers using 2 different methods, and the result should be an integer array. 

In [16]:
rng = np.random.default_rng(seed=21)
q15 = rng.integers(0,10, size=(8))
print("Original array: ")
print(q15)

q15[1] = 2.3
print("New array: ")
print(q15)

method1 = q15.astype(int)
method2 = np.floor(q15).astype(int)
print("Method 1: ")
print(method1)

print("Method 2: ")
print(method2)

Original array: 
[3 7 3 6 4 7 3 0]
New array: 
[3 2 3 6 4 7 3 0]
Method 1: 
[3 2 3 6 4 7 3 0]
Method 2: 
[3 2 3 6 4 7 3 0]


### 2. Operations on Numpy Arrays: total 50 points

In [17]:
import numpy as np

1). Find the index of 5th repetition of number 1 in the given array x.

x: [1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2]

In [18]:
x = [1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2]
target_val = 1
target_rep = 5
counter = 0
for i,val in enumerate(x):
    if val == target_val:
        counter = counter+1
        if target_rep == counter:
            print("Index of the 5th respresentation of number 1 is "+ str(i))

Index of the 5th respresentation of number 1 is 8


2). Use np.arange to get an array [1, 2, 3, ..., 9]. Split x into 3 sub-arrays, the length of each sub-array is 4, 2, and 3.

In [19]:
#without loop
q2 = np.arange(1,10)
sub1 = q2[:4]
sub2 = q2[4:6]
sub3 = q2[6:]
final_q2_1 = [sub1,sub2,sub3]
final_q2_2 = [sub1.tolist(),sub2.tolist(),sub3.tolist()]
print("Final array is (without loop): ")
print(final_q2_2)

#with loop
q2 = np.arange(1,10)
lengths = [4,2,3]
subarrays = []
start = 0
for i in lengths:
    end = start+i
    subarrays.append(q2[start:end])
    start = end
print("Final array is (with loop): ")
for i in subarrays:
    print(i)

Final array is (without loop): 
[[1, 2, 3, 4], [5, 6], [7, 8, 9]]
Final array is (with loop): 
[1 2 3 4]
[5 6]
[7 8 9]


3). Use np.arange to generate the following 2D array:

[[ 0., 1., 2., 3.],

 [ 4., 5., 6., 7.],

 [ 8., 9., 10., 11.],

 [ 12., 13., 14., 15.]]
Use np.split to split the array into left and right halves.

[[ 0,  1],

 [ 4,  5],

 [ 8,  9],

 [12, 13]]
and

[[ 2,  3],

 [ 6,  7],

 [10, 11],

 [14, 15]]

In [20]:
q3 = np.zeros((4,4))
q3[:] = np.arange(16).reshape(4,4)
print("2D array is: ")
print(q3)

q3 = np.arange(16).reshape(4,4)
lefthalf, righthalf = np.split(q3, 2, axis = 1)
print("left half is: ")
print(lefthalf)
print("right half is: ")
print(righthalf)

print("left half is: ")
print(lefthalf.tolist())
print("right half is: ")
print(righthalf.tolist())

2D array is: 
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
left half is: 
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
right half is: 
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
left half is: 
[[0, 1], [4, 5], [8, 9], [12, 13]]
right half is: 
[[2, 3], [6, 7], [10, 11], [14, 15]]


4). Given an 2D array:

[[5,10,15],

 [20,25,30],

 [35,40,45]]

(1) Slicing to get the sub-array [[10,15], [25,30]]  (4 points)

(2) Getting individual element value "20"  (2 points)

In [21]:
q4 = np.array([[5,10,15],[20,25,30], [35,40,45]])

q4_1 = q4[0:2,1:3].tolist()
print("1. Sliced array is: ")
print(q4_1)

q4_2 = q4[1,0]
print("2. Element found: ")
print(q4_2)

1. Sliced array is: 
[[10, 15], [25, 30]]
2. Element found: 
20


5). Let x be an array: 

[[ 1 2 3],

 [ 4 5 6]].
and y be an array

[[ 7 8 9],

 [10 11 12]].
Concatenate x and y so that a new array looks like

[[1, 2, 3, 7, 8, 9],

 [4, 5, 6, 10, 11, 12]].

In [22]:
x = np.array([[ 1, 2, 3],[ 4, 5, 6]])
y = np.array([[ 7, 8, 9],[10, 11, 12]])
q5 = np.concatenate((x,y), axis = 1)
print("Concatenated array is: ")
print(q5.tolist())

Concatenated array is: 
[[1, 2, 3, 7, 8, 9], [4, 5, 6, 10, 11, 12]]


6). Compute the min/max (min is divided by max) for each row for a given 2d array, in which integer values range from 1 to 10 [1,10) and shape is (5,3). (4 points)

Here requires a random seed to keep the same value from the random generator. (2 points)

In [23]:
import numpy as np
rng = np.random.default_rng(seed=21)
q6 = rng.integers(1,10, size=(5, 3))
print("2D array is: "+str(q6))

for i,val in enumerate(q6):
    min_val = np.min(q6[i])
    max_val = np.max(q6[i])
    div_val = min_val/max_val
    print("min/max for row "+str(i)+" where min is "+str(min_val)+" and max is "+str(max_val)+ " is "+str(div_val))

2D array is: [[3 8 4]
 [6 5 7]
 [4 1 3]
 [6 6 9]
 [3 4 9]]
min/max for row 0 where min is 3 and max is 8 is 0.375
min/max for row 1 where min is 5 and max is 7 is 0.7142857142857143
min/max for row 2 where min is 1 and max is 4 is 0.25
min/max for row 3 where min is 6 and max is 9 is 0.6666666666666666
min/max for row 4 where min is 3 and max is 9 is 0.3333333333333333


7). Normalize a 5x5 random matrix:

Tips: a normalization operates like: (the array - the mean)/the standard deviation

In [24]:
rng = np.random.default_rng(seed=21)
q7 = rng.integers(1,10, size=(5, 5))
print("5x5 matrix is: ")
print(q7)

mean_q7 = np.mean(q7)
print("Mean of matrix is: ")
print(mean_q7)

std_q7 = np.std(q7)
print("Standard deviation of matrix is: ")
print(std_q7)

normal_q7 = (q7 - mean_q7)/std_q7
print("Normalized matrix is: ")
print(normal_q7)

5x5 matrix is: 
[[3 8 4 6 5]
 [7 4 1 3 6]
 [6 9 3 4 9]
 [2 7 9 9 7]
 [9 2 7 7 5]]
Mean of matrix is: 
5.68
Standard deviation of matrix is: 
2.44491308638978
Normalized matrix is: 
[[-1.09615348  0.94890899 -0.68714099  0.130884   -0.2781285 ]
 [ 0.53989649 -0.68714099 -1.91417847 -1.09615348  0.130884  ]
 [ 0.130884    1.35792148 -1.09615348 -0.68714099  1.35792148]
 [-1.50516598  0.53989649  1.35792148  1.35792148  0.53989649]
 [ 1.35792148 -1.50516598  0.53989649  0.53989649 -0.2781285 ]]


8). Convert 3 arrays into a 1d array.

arr1: 0,1,2

arr2: 3,4,5,6

arr3: 7,8,9
Generate the 3 arrays by numpy arange()

Desired Output:

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr1 = np.arange(0,3)
print("Array 1 is: "+str(arr1))
arr2 = np.arange(3,7)
print("Array 2 is: "+str(arr2))
arr3 = np.arange(7,10)
print("Array 3 is: "+str(arr3))
q8 = np.concatenate([arr1,arr2,arr3])
print("Converted array is: ")
q8

Array 1 is: [0 1 2]
Array 2 is: [3 4 5 6]
Array 3 is: [7 8 9]
Converted array is: 


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

9). Get all items between 15 and 55 from aa, math expression: [15,55].

The aa is uniformly distributed integers in a 1D array (size=20) with given values (<100). Requires defining a seed.

In [26]:
rng = np.random.default_rng(seed=21)
aa = rng.integers(1,100, size=(20))
print("Array aa is: ")
print(aa)
aa_15_55 = aa[(aa>=15) & (aa<=55)]
print("Items between 15 and 55 from aa is: ")
print(aa_15_55)

Array aa is: 
[30 78 39 60 47 71 35  9 30 63 62 98 24 42 94 12 70 95 91 67]
Items between 15 and 55 from aa is: 
[30 39 47 35 30 24 42]


10). Get the positions where elements of a and b match.                 4 points

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("Positions (not index) where elements of a and b match are: ")
for i in range(a.size):
    if a[i]==b[i]:
        print(i+1)

Positions (not index) where elements of a and b match are: 
2
4
6
8


11). Use arange() to create an array from 0 to 20 ( [0,20) ); replace all odd numbers with -1. 

In [28]:
q11 = np.arange(0,20)
print("Original array is: ")
print(q11)
for i,val in enumerate(q11):
    if val%2!=0:
        q11[i] = -1
print("New array is: ")
print(q11)

Original array is: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
New array is: 
[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1]


12). Considering a four dimensions array (3,4,3,4) with the values 0-9 randomly, how to get sum over the last two axis at once? 

In [29]:
rng = np.random.default_rng(seed=21)
q12 = rng.integers(0,10, size=(3,4,3,4))
print("4D array is: ")
print(q12)

sum_last2_q12 = np.sum(q12, axis = (-2, -1))
print("Sum over the last two axis at once is: ")
print(sum_last2_q12)

4D array is: 
[[[[3 7 3 6]
   [4 7 3 0]
   [2 6 6 9]]

  [[2 4 9 1]
   [7 9 9 6]
   [8 1 7 6]]

  [[5 9 8 2]
   [9 8 3 6]
   [7 2 2 1]]

  [[4 9 3 3]
   [9 4 0 6]
   [7 4 9 0]]]


 [[[8 2 7 4]
   [6 7 8 6]
   [6 4 0 1]]

  [[1 7 1 1]
   [2 7 3 4]
   [6 5 4 3]]

  [[9 2 7 1]
   [4 6 2 2]
   [1 0 2 1]]

  [[6 9 0 7]
   [4 5 9 4]
   [1 8 8 2]]]


 [[[5 6 1 0]
   [0 6 6 9]
   [5 7 4 0]]

  [[3 5 6 3]
   [1 9 2 0]
   [4 0 6 0]]

  [[3 3 7 8]
   [6 5 2 6]
   [7 0 5 1]]

  [[0 3 7 6]
   [8 7 3 5]
   [2 2 6 1]]]]
Sum over the last two axis at once is: 
[[56 69 62 58]
 [59 44 37 63]
 [49 39 53 50]]
